### ISSUE TITLE
fix typos

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CCPPStandardNames#11]
x_wind: Horizontal wind in a direction perdendicular to y_wind

y_wind: Horizontal wind in a direction perdendicular to x_wind

"Perpendicular" is mistyped

Units for avogadro are "molecule mole-1", but will not match the current CAM definition (no change needed here)

**Comment by nusbaume** [comment]
Just double-checking that you meant `Perpendicular`?

**Comment by cacraigucar** [comment]
> Just double-checking that you meant `Perpendicular`?

Yup - even my typo correction has a typo!  I was concentrating so hard on the "d" to "p".  The good news is that I typed it right when I put it into CAMDEN!

**Comment by cacraigucar** [comment]
constituent_mixing_ratio: Constituent mixing ratio
real(kind=kind_phys): units = kg/kg moist or dry air depending on type

Units should be "kg kg-1"

**Comment by cacraigucar** [comment]
cell_weight units should be "1"

**Comment by cacraigucar** [comment]
"pressure_dependent_XXX" needs to become "composition_dependent_XXX"

**Comment by nusbaume** [comment]
Also adding a note here that `gravitational_acceleration` should probably be moved from `coordinates` to `constants`.

**Comment by climbfuji** [comment]
`gravitational_acceleration` is not a constant. `gravitational_constant` is, but `gravitational_acceleration` depends on the distance from the center of the Earth.

**Comment by nusbaume** [comment]
Yeah we kept going back and forth on this, because although you are correct that gravity varies as a function of distance from the planet's center, our low and mid-top models treat it as a strict constant of ~9.81 m s-2.

Regardless, I am happy to move it to a different section in the standard names dictionary to indicate that it should  change with height, at least in the real world.  Would `state_variables` work?  

I mostly don't want it in `coordinates`  because it doesn't seem directly related to the geospatial grid itself.  In other words if you output a physical quantity `X` to a NetCDF file it would seem weird (to me at least) to have its dimensions be  `X(lat, lon, gravity)`.   That being said, if you have a counter example then I am happy to just keep it where it is.
