### ISSUE TITLE
gravity and the "coordinates" section

### ISSUE THREAD

**Issue by nusbaume** [ESCOMP/CCPPStandardNames#39]
Currently the standard name `gravitational_acceleration` is located under the `coordinates` section.  However,  I at least tend to not think of gravity as a coordinate, which then led to a discussion of what a "coordinate" actually means, at least in CCPP standard name world, which might be good to write down somewhere.  To start the discussion I can think of two possibilities for what constitutes a "coordinate":

1.  A quantity that is only a function or attribute of the model grid, and which is solely used to determine one's location in space.  With this definition arguably only `latitude` and `longitude` in the current dictionary file would classify as "coordinates".
2.  Any quantity that can be calculated using only geospatial information like the model grid and planet radius.  With this definition the `cell_area` and `cell_weight` would also be "coordinate" variables.

If we use definition 2 above then `gravitational_acceleration` could also stay given that is generally only a function of the distance from the planet's gravitational center.  However, one could also make the argument that if simulating non-Earth planets then the planet's mass also comes into play, which would then mean that `gravitational_acceleration` might be better included in a different section, like `state_variables`.

Finally, although in reality gravity varies as a function of one's location in space, many models treat it as a constant.  Would it also be beneficial to include a new standard name, say `standard_acceleration_of_gravity`, to represent this model constant?

Anyways, happy to hear any thoughts or opinions on this topic.  Thanks!

**Comment by mkavulich** [comment]
@nusbaume Thanks for starting the discussion on this topic. I've had some time to think about it and do some reading and I have a few thoughts.

First of all, as you suggest, there are a few different meanings of "gravitational acceleration" as a variable name in earth system modeling. Admittedly the subtleties in how and when these are used are a bit outside my wheelhouse, but there are at least three different definitions of gravitational acceleration from what I can ascertain:

1. A scalar gravitational constant, representing the acceleration due to gravity at earth's surface. The definition of "earth's surface" here often is undefined or vaguely defined; when it is specifically defined it is usually is in reference to the value at earth's mean radius, or as in the [physical constants dictionary](https://github.com/ESCOMP/PhysicalConstantsDictionary/blob/master/pcd.yaml), the value at sea level at a geodetic latitude of 45 degrees.
2. A 1-d vertically varying gravity, which takes into account the reduced gravitational acceleration with increating height. While this does not appear to be widely used, it may be important for whole-/upper-atmosphere modeling since its effect is [most significant in the upper atmosphere](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2008JA013081), and there have been [some recent papers](https://journals-ametsoc-org.cuucar.idm.oclc.org/view/journals/mwre/aop/MWR-D-22-0320.1/MWR-D-22-0320.1.xml) documenting its use in NAVGEM (not in the dynamical core itself, but in the calculation of some diagnostic variables in physics). 
3. A 3-d gravitational vector field, taking into account both the reduction in gravitational force with height and horizontal gravitational forces due to local geoid anomalies. This appears to be uncommon and probably not in any widely-used model but is advocated by [at least one paper](https://www.sciencedirect.com/science/article/pii/S0377026523000209) I could find.

It does seem wise to support at least two different standard names for gravitational acceleration: a constant (definition 1 above) and a vertically varying gravitational acceleration (definition 2 above), since these both seem to have at least some active use in earth system modeling. Definition 1 would better fit in the "constants" section, while definition 2 would have to appear elsewhere. 

RE: gravity as a "coordinate", it makes *some* sense with respect to definition 2 listed above, where gravity monotonically decreases with height. I do think that this can be misleading, however with a better description/definition I think its presence in this section could be justified. I don't think it belongs in the same section as "state variables", since it is not really a temporal variable in the same way that other traditional state variables are. So it's unclear to me where this variable would fit if not in the "coordinates" section.
